"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { VERSION, MANIFEST_REL } = require("./constants");
const {
  copyTracked,
  writeTracked,
  writeManifest,
  resolveUnderRoot,
  sha256Text,
  sha256File,
  needsOverwriteConfirm,
  confirmContinue,
  print,
} = require("./shared");

function parseActionInputs(actionYml) {
  const inputs = [];
  const lines = String(actionYml).split(/\r?\n/);
  let inInputs = false;
  for (const line of lines) {
    if (/^inputs:\s*$/.test(line)) {
      inInputs = true;
      continue;
    }
    if (inInputs && /^\S/.test(line) && !line.startsWith(" ")) {
      break;
    }
    if (inInputs) {
      const match = line.match(/^  ([A-Za-z0-9_]+):\s*$/);
      if (match) inputs.push(match[1]);
    }
  }
  return inputs;
}

function workflowYaml(inputs) {
  const withLines = inputs.map((name) => {
    if (name === "endpoint") {
      return `          endpoint: \${{ vars.PRIVACYTRACE_CONNECTOR_URL }}`;
    }
    if (name === "token") {
      return `          token: \${{ secrets.PRIVACYTRACE_CONNECTOR_TOKEN }}`;
    }
    if (name === "repo") return `          repo: \${{ github.repository }}`;
    if (name === "sha") return `          sha: \${{ github.sha }}`;
    if (name === "run_id") return `          run_id: \${{ github.run_id }}`;
    if (name === "workflow") return `          workflow: \${{ github.workflow }}`;
    return `          ${name}: ""`;
  });
  return `# Generated by privacytrace-connect. Repository/local Action — not GitHub Marketplace.
# Store PRIVACYTRACE_CONNECTOR_URL as an Actions variable.
# Store PRIVACYTRACE_CONNECTOR_TOKEN as an Actions secret.
# Never put the token in this file.
name: PrivacyTrace connector
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  privacytrace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PrivacyTrace provenance
        uses: ./.github/actions/privacytrace
        with:
${withLines.join("\n")}
`;
}

async function addGithub(ctx) {
  const { cwd, sourceRoot, endpoint, flags, stdout, stdin, env, tracker, service, environment } = ctx;
  const gitDir = path.join(cwd, ".git");
  if (!fs.existsSync(gitDir)) {
    throw new Error("A .git directory is required for add github-actions. Initialise a git repository first.");
  }
  const srcDir = path.join(sourceRoot, "connectors", "github-actions");
  const actionSrc = path.join(srcDir, "action.yml");
  const indexSrc = path.join(srcDir, "index.js");
  const actionRel = ".github/actions/privacytrace/action.yml";
  const indexRel = ".github/actions/privacytrace/index.js";
  const workflowRel = ".github/workflows/privacytrace.yml";
  const actionBody = fs.readFileSync(actionSrc, "utf8");
  const inputs = parseActionInputs(actionBody);
  const wfBody = workflowYaml(inputs);
  const plan = [
    "Git repository detected. No commit, push, PR, or remote secrets API calls.",
    `Copy action.yml → ${actionRel}`,
    `Copy index.js → ${indexRel}`,
    `Write ${workflowRel} from action.yml inputs (token via \${{ secrets.PRIVACYTRACE_CONNECTOR_TOKEN }})`,
    `Write ${MANIFEST_REL} (no token)`,
    "permissions: contents: read",
  ];

  return {
    plan,
    summary: [
      ["Local GitHub Action", "PLANNED"],
      ["Hosted GitHub workflow", "REAL PLATFORM PENDING"],
    ],
    apply: async () => {
      const destAction = resolveUnderRoot(cwd, actionRel);
      const destIndex = resolveUnderRoot(cwd, indexRel);
      const destWf = resolveUnderRoot(cwd, workflowRel);
      if (needsOverwriteConfirm(destWf, sha256Text(wfBody))) {
        print(stdout, `Workflow exists with different content: ${destWf}`);
        const overwrite = await confirmContinue({ stdin, stdout, env });
        if (!overwrite) throw new Error("Overwrite declined.");
      }
      copyTracked(tracker, actionSrc, destAction);
      copyTracked(tracker, indexSrc, destIndex);
      writeTracked(tracker, destWf, wfBody);
      writeManifest(
        cwd,
        {
          version: VERSION,
          connector: "github-actions",
          timestamp: new Date().toISOString(),
          paths: [actionRel, indexRel, workflowRel],
          hashes: {
            [actionRel]: sha256File(destAction),
            [indexRel]: sha256File(destIndex),
            [workflowRel]: sha256Text(wfBody),
          },
          url: endpoint,
          service,
          environment,
        },
        tracker,
      );
      print(stdout, "LOCAL ACTION INSTALLATION VERIFIED");
      print(stdout, "HOSTED GITHUB WORKFLOW PENDING");
      return {
        code: 0,
        summary: [
          ["Local GitHub Action", "INSTALLED"],
          ["Workflow file", "CONFIGURED"],
          ["Hosted GitHub workflow", "REAL PLATFORM PENDING"],
        ],
      };
    },
  };
}

module.exports = { addGithub, parseActionInputs, workflowYaml };
