"""Phase 12.1 — PDF rendering for final investigation reports (ReportLab)."""

from __future__ import annotations

import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas.final_report_schema import FinalInvestigationReport
from app.services import report_safety_service
from app.services.final_report_service import CONFIDENTIALITY_NOTE, ROOT_CAUSE_NOTE, SCANNER_NOTE


def _p(text: str | None, style: ParagraphStyle) -> Paragraph:
    safe = text or ""
    return Paragraph(safe.replace("\n", "<br/>"), style)


def render_final_report_pdf(report: FinalInvestigationReport) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title=f"Final Investigation Report {report.metadata.incident_id}",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=12,
    )
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6)
    body = styles["BodyText"]
    small = ParagraphStyle("Small", parent=body, fontSize=9, textColor=colors.grey)

    story: list[Any] = []
    story.append(_p("PrivacyTrace-NP Final Investigation Report", title_style))
    story.append(_p(f"Incident ID: {report.metadata.incident_id}", body))
    story.append(_p(f"Generated: {report.metadata.generated_at}", body))
    story.append(_p(f"Generated by: {report.metadata.generated_by or 'system'}", body))
    story.append(_p(f"System version: {report.metadata.system_version}", body))
    story.append(Spacer(1, 0.2 * inch))
    story.append(_p(CONFIDENTIALITY_NOTE, small))
    story.append(PageBreak())

    story.append(_p("Executive Summary", h2))
    es = report.executive_summary
    for line in [
        f"Service: {es.affected_service}",
        f"Endpoint: {es.affected_endpoint}",
        f"Severity: {es.severity}",
        f"Top likely cause: {es.top_likely_cause}",
        f"Confidence band: {es.confidence_band}",
        f"Human review: {es.human_review_status}",
        f"Fix verification: {es.fix_verification_status}",
    ]:
        story.append(_p(line, body))
    if es.incident_summary:
        story.append(_p(es.incident_summary, body))

    story.append(_p("Incident Details", h2))
    inc = report.incident
    for line in [
        f"Title: {inc.title}",
        f"Status: {inc.status}",
        f"Severity: {inc.severity}",
        f"First seen: {inc.first_seen}",
        f"Last seen: {inc.last_seen}",
    ]:
        story.append(_p(line, body))

    story.append(_p("Live Monitor Summary and Privacy Alert Timeline", h2))
    live = report.live_monitor_summary
    for line in [
        f"Incident source: {live.source}",
        f"Linked privacy alerts: {live.linked_alert_count}",
        f"Root-cause evidence strength: {live.evidence_strength}",
        f"Alert-to-incident flow: {live.alert_to_incident_flow}",
    ]:
        story.append(_p(line, body))
    if live.alerts:
        data = [["Alert", "First seen", "Last seen", "Repeat", "Service / endpoint", "Masked values"]]
        for alert in live.alerts:
            data.append(
                [
                    alert.alert_id,
                    str(alert.first_seen or alert.alert_time or ""),
                    str(alert.last_seen or ""),
                    str(alert.repeat_count),
                    f"{alert.service_name or ''} {alert.endpoint or ''}".strip(),
                    ", ".join(alert.masked_values),
                ]
            )
        table = Table(
            data,
            colWidths=[0.9 * inch, 1.15 * inch, 1.15 * inch, 0.45 * inch, 1.2 * inch, 1.45 * inch],
        )
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#edf2f7")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("FONTSIZE", (0, 0), (-1, -1), 7),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(table)
    else:
        story.append(_p("No linked live alerts.", body))
    for label, count in live.evidence_source_summary.items():
        story.append(_p(f"Evidence source: {label} ({count})", body))
    for item in live.missing_evidence:
        story.append(_p(f"Missing evidence: {item}", body))
    story.append(_p(live.note, small))
    for item in live.limitations:
        story.append(_p(f"Limitation: {item}", small))

    story.append(_p("Detection Summary", h2))
    if report.detections:
        data = [["Detection", "Type", "Masked value", "Severity"]]
        for d in report.detections:
            data.append([d.detection_id, d.sensitive_type, d.masked_value, d.severity or ""])
        table = Table(data, colWidths=[1.2 * inch, 1.1 * inch, 2.2 * inch, 0.8 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#edf2f7")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(table)
    else:
        story.append(_p("No detections recorded.", body))

    story.append(_p("Evidence Chain", h2))
    if report.evidence_chain:
        data = [["Evidence ID", "Type", "File", "Role"]]
        for e in report.evidence_chain:
            data.append(
                [e.evidence_id, e.evidence_type, e.file_name[:40], e.role_in_investigation[:35]]
            )
        table = Table(data, colWidths=[1.1 * inch, 1.0 * inch, 1.5 * inch, 2.0 * inch])
        table.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("FONTSIZE", (0, 0), (-1, -1), 8)]))
        story.append(table)

    story.append(_p("Root-Cause Ranking", h2))
    for item in report.root_cause_ranking:
        story.append(
            _p(
                f"Rank {item.rank}: {item.cause_name} "
                f"(band {item.confidence_band}) — evidence: {', '.join(item.supporting_evidence_ids)}",
                body,
            )
        )
    story.append(_p(ROOT_CAUSE_NOTE, small))
    story.append(_p("Why this cause was ranked highest", h2))
    for item in report.explainability_summary.get("why_ranked_highest") or []:
        story.append(_p(f"• {item.get('reason') or item}", body))
    story.append(_p(f"Safe conclusion: {report.safe_conclusion}", body))

    story.append(_p("Contradicting evidence", h2))
    contradictions = report.explainability_summary.get("contradicting_evidence") or []
    if contradictions:
        for item in contradictions:
            story.append(_p(f"• {item.get('evidence_id')}: {item.get('reason')}", body))
    else:
        story.append(_p("No contradicting evidence captured.", body))

    story.append(_p("ScannerBridge-NP Supporting Evidence", h2))
    if report.scannerbridge_evidence:
        for s in report.scannerbridge_evidence:
            story.append(
                _p(
                    f"{s.scanner_evidence_id}: {s.detector_name} — {s.masked_value} "
                    f"(relevance {s.causal_relevance_score})",
                    body,
                )
            )
        story.append(_p(SCANNER_NOTE, small))
    else:
        story.append(_p("No external scanner evidence linked.", body))

    story.append(_p("Guarded Explanation", h2))
    ge = report.guarded_explanation
    story.append(_p(ge.explanation_text or ge.not_generated_message, body))

    story.append(_p("Human Review", h2))
    hr = report.human_review
    if hr.reviewer or hr.decision:
        story.append(_p(f"Reviewer: {hr.reviewer} — Decision: {hr.decision}", body))
        if hr.comment:
            story.append(_p(hr.comment, body))
    else:
        story.append(_p(hr.not_completed_message, body))

    story.append(_p("Remediation Action", h2))
    for action in report.remediation_actions:
        story.append(_p(f"Action: {action}", body))

    story.append(_p("Fix Verification", h2))
    fv = report.fix_verification
    if fv.verification_status:
        story.append(_p(f"Status: {fv.verification_status}", body))
    else:
        story.append(_p(fv.not_completed_message, body))

    story.append(_p("Recommendations", h2))
    for rec in report.recommendations:
        story.append(_p(f"• {rec}", body))

    story.append(_p("Privacy and Safety Controls", h2))
    for ctrl in report.privacy_safety_controls:
        story.append(_p(f"• {ctrl}", body))

    story.append(_p("Limitations", h2))
    for lim in report.limitations:
        story.append(_p(f"• {lim}", body))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    report_safety_service.validate_text_blob(pdf_bytes.decode("latin-1", errors="ignore"))
    return pdf_bytes
