"""Central role-based permission checks for PrivacyTrace-NP."""

from __future__ import annotations

from app.models.enums import UserRole

# Permission identifiers used by require_permission() dependencies.
PERMISSION_INCIDENT_READ = "incident:read"
PERMISSION_EVIDENCE_READ = "evidence:read"
PERMISSION_EVIDENCE_UPLOAD = "evidence:upload"
PERMISSION_EVIDENCE_LOAD_SAMPLE = "evidence:load_sample"
PERMISSION_WORKFLOW_PARSE = "workflow:parse"
PERMISSION_WORKFLOW_DETECT = "workflow:detect"
PERMISSION_WORKFLOW_ANALYSE = "workflow:analyse"
PERMISSION_EXPLANATION_GENERATE = "explanation:generate"
PERMISSION_INCIDENT_REVIEW = "incident:review"
PERMISSION_INCIDENT_REVIEW_READ = "incident:review_read"
PERMISSION_AUDIT_READ = "audit:read"
PERMISSION_FIX_VERIFY = "fix:verify"
PERMISSION_FIX_READ = "fix:read"
PERMISSION_REPORT_GENERATE = "report:generate"
PERMISSION_METRICS_READ = "metrics:read"
PERMISSION_METRICS_RUN = "metrics:run"
PERMISSION_USER_MANAGE = "user:manage"
PERMISSION_INTEGRATION_INGEST = "integration:ingest"
PERMISSION_INTEGRATION_EXPORT = "integration:export"
PERMISSION_INTEGRATION_READ = "integration:read"
PERMISSION_INTEGRATION_TOKEN_MANAGE = "integration:token_manage"
PERMISSION_SCANNER_BRIDGE_IMPORT = "scanner_bridge:import"
PERMISSION_SCANNER_BRIDGE_READ = "scanner_bridge:read"
PERMISSION_LIVE_MONITOR_READ = "live_monitor:read"
PERMISSION_LIVE_MONITOR_CONTROL = "live_monitor:control"
PERMISSION_LIVE_MONITOR_INGEST = "live_monitor:ingest"
PERMISSION_LIVE_MONITOR_INCIDENT = "live_monitor:incident"
PERMISSION_LIVE_MONITOR_DISMISS = "live_monitor:dismiss"
PERMISSION_AI_REMEDIATION_READ = "ai_remediation:read"
PERMISSION_AI_REMEDIATION_GENERATE = "ai_remediation:generate"
PERMISSION_AI_REMEDIATION_REVIEW = "ai_remediation:review"
PERMISSION_PRIVACY_IMPACT_READ = "privacy_impact:read"
PERMISSION_PRIVACY_IMPACT_ASSESS = "privacy_impact:assess"
PERMISSION_PRIVACY_IMPACT_APPROVE = "privacy_impact:approve"
PERMISSION_BREACH_ALERT_READ = "breach_alert:read"
PERMISSION_BREACH_ALERT_MANAGE = "breach_alert:manage"
PERMISSION_AFFECTED_SUBJECT_READ = "affected_subject:read"
PERMISSION_AFFECTED_SUBJECT_RESOLVE = "affected_subject:resolve"
PERMISSION_CONTAINMENT_READ = "containment:read"
PERMISSION_CONTAINMENT_APPROVE = "containment:approve"
PERMISSION_CONTAINMENT_EXECUTE = "containment:execute"
PERMISSION_CUSTOMER_NOTIFICATION_READ = "customer_notification:read"
PERMISSION_CUSTOMER_NOTIFICATION_DRAFT = "customer_notification:draft"
PERMISSION_CUSTOMER_NOTIFICATION_APPROVE = "customer_notification:approve"
PERMISSION_CUSTOMER_NOTIFICATION_QUEUE = "customer_notification:queue"
PERMISSION_BREACH_DECISION_READ = "breach_decision:read"
PERMISSION_BREACH_DECISION_CREATE = "breach_decision:create"
PERMISSION_BREACH_DECISION_REVIEW = "breach_decision:review"
PERMISSION_BREACH_DECISION_APPROVE = "breach_decision:approve"
PERMISSION_PROVENANCE_READ = "provenance:read"
PERMISSION_PROVENANCE_VALIDATE = "provenance:validate"
PERMISSION_INTEGRITY_READ = "integrity:read"
PERMISSION_INTEGRITY_VERIFY = "integrity:verify"
PERMISSION_COUNTERFACTUAL_READ = "counterfactual:read"
PERMISSION_COUNTERFACTUAL_RUN = "counterfactual:run"
PERMISSION_ALERT_OPERATIONS_READ = "alert_operations:read"
PERMISSION_ALERT_OPERATIONS_MANAGE = "alert_operations:manage"
PERMISSION_TIMELINE_READ = "timeline:read"
PERMISSION_PREVENTIVE_CONTROL_READ = "preventive_control:read"
PERMISSION_PREVENTIVE_CONTROL_GENERATE = "preventive_control:generate"
PERMISSION_PREVENTIVE_CONTROL_REVIEW = "preventive_control:review"
PERMISSION_PREVENTIVE_CONTROL_APPROVE = "preventive_control:approve"
PERMISSION_PREVENTIVE_CONTROL_IMPLEMENT = "preventive_control:implement"
PERMISSION_PREVENTIVE_CONTROL_VERIFY = "preventive_control:verify"
PERMISSION_TAXONOMY_READ = "taxonomy:read"
PERMISSION_TAXONOMY_VALIDATE = "taxonomy:validate"
PERMISSION_EXPOSURE_PROFILE_READ = "exposure_profile:read"
PERMISSION_EXPOSURE_PROFILE_RECALCULATE = "exposure_profile:recalculate"
PERMISSION_EXPOSURE_PROFILE_REVIEW = "exposure_profile:review"
PERMISSION_RESTRICTED_DETECTION_READ = "restricted_detection:read"

_ALL_PERMISSIONS = {
    PERMISSION_INCIDENT_READ,
    PERMISSION_EVIDENCE_READ,
    PERMISSION_EVIDENCE_UPLOAD,
    PERMISSION_EVIDENCE_LOAD_SAMPLE,
    PERMISSION_WORKFLOW_PARSE,
    PERMISSION_WORKFLOW_DETECT,
    PERMISSION_WORKFLOW_ANALYSE,
    PERMISSION_EXPLANATION_GENERATE,
    PERMISSION_INCIDENT_REVIEW,
    PERMISSION_INCIDENT_REVIEW_READ,
    PERMISSION_AUDIT_READ,
    PERMISSION_FIX_VERIFY,
    PERMISSION_FIX_READ,
    PERMISSION_REPORT_GENERATE,
    PERMISSION_METRICS_READ,
    PERMISSION_METRICS_RUN,
    PERMISSION_USER_MANAGE,
    PERMISSION_INTEGRATION_INGEST,
    PERMISSION_INTEGRATION_EXPORT,
    PERMISSION_INTEGRATION_READ,
    PERMISSION_INTEGRATION_TOKEN_MANAGE,
    PERMISSION_SCANNER_BRIDGE_IMPORT,
    PERMISSION_SCANNER_BRIDGE_READ,
    PERMISSION_LIVE_MONITOR_READ,
    PERMISSION_LIVE_MONITOR_CONTROL,
    PERMISSION_LIVE_MONITOR_INGEST,
    PERMISSION_LIVE_MONITOR_INCIDENT,
    PERMISSION_LIVE_MONITOR_DISMISS,
    PERMISSION_AI_REMEDIATION_READ,
    PERMISSION_AI_REMEDIATION_GENERATE,
    PERMISSION_AI_REMEDIATION_REVIEW,
    PERMISSION_PRIVACY_IMPACT_READ,
    PERMISSION_PRIVACY_IMPACT_ASSESS,
    PERMISSION_PRIVACY_IMPACT_APPROVE,
    PERMISSION_BREACH_ALERT_READ,
    PERMISSION_BREACH_ALERT_MANAGE,
    PERMISSION_AFFECTED_SUBJECT_READ,
    PERMISSION_AFFECTED_SUBJECT_RESOLVE,
    PERMISSION_CONTAINMENT_READ,
    PERMISSION_CONTAINMENT_APPROVE,
    PERMISSION_CONTAINMENT_EXECUTE,
    PERMISSION_CUSTOMER_NOTIFICATION_READ,
    PERMISSION_CUSTOMER_NOTIFICATION_DRAFT,
    PERMISSION_CUSTOMER_NOTIFICATION_APPROVE,
    PERMISSION_CUSTOMER_NOTIFICATION_QUEUE,
    PERMISSION_BREACH_DECISION_READ,
    PERMISSION_BREACH_DECISION_CREATE,
    PERMISSION_BREACH_DECISION_REVIEW,
    PERMISSION_BREACH_DECISION_APPROVE,
    PERMISSION_PROVENANCE_READ,
    PERMISSION_PROVENANCE_VALIDATE,
    PERMISSION_INTEGRITY_READ,
    PERMISSION_INTEGRITY_VERIFY,
    PERMISSION_COUNTERFACTUAL_READ,
    PERMISSION_COUNTERFACTUAL_RUN,
    PERMISSION_ALERT_OPERATIONS_READ,
    PERMISSION_ALERT_OPERATIONS_MANAGE,
    PERMISSION_TIMELINE_READ,
    PERMISSION_PREVENTIVE_CONTROL_READ,
    PERMISSION_PREVENTIVE_CONTROL_GENERATE,
    PERMISSION_PREVENTIVE_CONTROL_REVIEW,
    PERMISSION_PREVENTIVE_CONTROL_APPROVE,
    PERMISSION_PREVENTIVE_CONTROL_IMPLEMENT,
    PERMISSION_PREVENTIVE_CONTROL_VERIFY,
    PERMISSION_TAXONOMY_READ,
    PERMISSION_TAXONOMY_VALIDATE,
    PERMISSION_EXPOSURE_PROFILE_READ,
    PERMISSION_EXPOSURE_PROFILE_RECALCULATE,
    PERMISSION_EXPOSURE_PROFILE_REVIEW,
    PERMISSION_RESTRICTED_DETECTION_READ,
}

_ROLE_PERMISSIONS: dict[UserRole, frozenset[str]] = {
    UserRole.ADMIN: _ALL_PERMISSIONS,
    UserRole.ORGANISATION_ADMIN: _ALL_PERMISSIONS,
    UserRole.PLATFORM_ADMIN: _ALL_PERMISSIONS,
    UserRole.SECURITY_ANALYST: frozenset(
        {
            PERMISSION_INCIDENT_READ,
            PERMISSION_EVIDENCE_READ,
            PERMISSION_EVIDENCE_UPLOAD,
            PERMISSION_EVIDENCE_LOAD_SAMPLE,
            PERMISSION_WORKFLOW_PARSE,
            PERMISSION_WORKFLOW_DETECT,
            PERMISSION_WORKFLOW_ANALYSE,
            PERMISSION_EXPLANATION_GENERATE,
            PERMISSION_INCIDENT_REVIEW,
            PERMISSION_INCIDENT_REVIEW_READ,
            PERMISSION_AUDIT_READ,
            PERMISSION_FIX_VERIFY,
            PERMISSION_FIX_READ,
            PERMISSION_REPORT_GENERATE,
            PERMISSION_METRICS_READ,
            PERMISSION_METRICS_RUN,
            PERMISSION_INTEGRATION_INGEST,
            PERMISSION_INTEGRATION_EXPORT,
            PERMISSION_INTEGRATION_READ,
            PERMISSION_INTEGRATION_TOKEN_MANAGE,
            PERMISSION_SCANNER_BRIDGE_IMPORT,
            PERMISSION_SCANNER_BRIDGE_READ,
            PERMISSION_LIVE_MONITOR_READ,
            PERMISSION_LIVE_MONITOR_CONTROL,
            PERMISSION_LIVE_MONITOR_INGEST,
            PERMISSION_LIVE_MONITOR_INCIDENT,
            PERMISSION_LIVE_MONITOR_DISMISS,
            PERMISSION_AI_REMEDIATION_READ,
            PERMISSION_AI_REMEDIATION_GENERATE,
            PERMISSION_AI_REMEDIATION_REVIEW,
            PERMISSION_PRIVACY_IMPACT_READ,
            PERMISSION_PRIVACY_IMPACT_ASSESS,
            PERMISSION_BREACH_ALERT_READ,
            PERMISSION_BREACH_ALERT_MANAGE,
            PERMISSION_AFFECTED_SUBJECT_READ,
            PERMISSION_AFFECTED_SUBJECT_RESOLVE,
            PERMISSION_CONTAINMENT_READ,
            PERMISSION_CUSTOMER_NOTIFICATION_READ,
            PERMISSION_CUSTOMER_NOTIFICATION_DRAFT,
            PERMISSION_BREACH_DECISION_READ,
            PERMISSION_BREACH_DECISION_CREATE,
            PERMISSION_BREACH_DECISION_REVIEW,
            PERMISSION_PROVENANCE_READ,
            PERMISSION_PROVENANCE_VALIDATE,
            PERMISSION_INTEGRITY_READ,
            PERMISSION_COUNTERFACTUAL_READ,
            PERMISSION_COUNTERFACTUAL_RUN,
            PERMISSION_ALERT_OPERATIONS_READ,
            PERMISSION_ALERT_OPERATIONS_MANAGE,
            PERMISSION_TIMELINE_READ,
            PERMISSION_PREVENTIVE_CONTROL_READ,
            PERMISSION_PREVENTIVE_CONTROL_GENERATE,
            PERMISSION_PREVENTIVE_CONTROL_REVIEW,
            PERMISSION_TAXONOMY_READ,
            PERMISSION_EXPOSURE_PROFILE_READ,
            PERMISSION_EXPOSURE_PROFILE_RECALCULATE,
            PERMISSION_EXPOSURE_PROFILE_REVIEW,
        }
    ),
    UserRole.DEVELOPER: frozenset(
        {
            PERMISSION_INCIDENT_READ,
            PERMISSION_EVIDENCE_READ,
            PERMISSION_FIX_READ,
            PERMISSION_INTEGRATION_READ,
            PERMISSION_SCANNER_BRIDGE_READ,
        }
    ),
    UserRole.DEVSECOPS_ENGINEER: frozenset(
        {
            PERMISSION_INCIDENT_READ,
            PERMISSION_EVIDENCE_READ,
            PERMISSION_EVIDENCE_UPLOAD,
            PERMISSION_WORKFLOW_PARSE,
            PERMISSION_WORKFLOW_DETECT,
            PERMISSION_WORKFLOW_ANALYSE,
            PERMISSION_FIX_VERIFY,
            PERMISSION_FIX_READ,
            PERMISSION_REPORT_GENERATE,
            PERMISSION_METRICS_READ,
            PERMISSION_INTEGRATION_INGEST,
            PERMISSION_INTEGRATION_EXPORT,
            PERMISSION_INTEGRATION_READ,
            PERMISSION_INTEGRATION_TOKEN_MANAGE,
            PERMISSION_SCANNER_BRIDGE_IMPORT,
            PERMISSION_SCANNER_BRIDGE_READ,
            PERMISSION_LIVE_MONITOR_READ,
            PERMISSION_LIVE_MONITOR_CONTROL,
            PERMISSION_LIVE_MONITOR_INGEST,
            PERMISSION_LIVE_MONITOR_INCIDENT,
            PERMISSION_AI_REMEDIATION_READ,
            PERMISSION_AI_REMEDIATION_GENERATE,
            PERMISSION_AI_REMEDIATION_REVIEW,
            PERMISSION_CONTAINMENT_READ,
            PERMISSION_CONTAINMENT_EXECUTE,
            PERMISSION_BREACH_DECISION_READ,
            PERMISSION_PROVENANCE_READ,
            PERMISSION_INTEGRITY_READ,
            PERMISSION_INTEGRITY_VERIFY,
            PERMISSION_COUNTERFACTUAL_READ,
            PERMISSION_ALERT_OPERATIONS_READ,
            PERMISSION_TIMELINE_READ,
            PERMISSION_PREVENTIVE_CONTROL_READ,
            PERMISSION_PREVENTIVE_CONTROL_IMPLEMENT,
            PERMISSION_PREVENTIVE_CONTROL_VERIFY,
            PERMISSION_TAXONOMY_READ,
            PERMISSION_EXPOSURE_PROFILE_READ,
        }
    ),
    UserRole.AUDITOR: frozenset(
        {
            PERMISSION_INCIDENT_READ,
            PERMISSION_INCIDENT_REVIEW_READ,
            PERMISSION_FIX_READ,
            PERMISSION_AUDIT_READ,
            PERMISSION_REPORT_GENERATE,
            PERMISSION_METRICS_READ,
            PERMISSION_INTEGRATION_EXPORT,
            PERMISSION_INTEGRATION_READ,
            PERMISSION_SCANNER_BRIDGE_READ,
            PERMISSION_LIVE_MONITOR_READ,
            PERMISSION_AI_REMEDIATION_READ,
            PERMISSION_PRIVACY_IMPACT_READ,
            PERMISSION_BREACH_ALERT_READ,
            PERMISSION_AFFECTED_SUBJECT_READ,
            PERMISSION_CONTAINMENT_READ,
            PERMISSION_CUSTOMER_NOTIFICATION_READ,
            PERMISSION_BREACH_DECISION_READ,
            PERMISSION_PROVENANCE_READ,
            PERMISSION_INTEGRITY_READ,
            PERMISSION_COUNTERFACTUAL_READ,
            PERMISSION_ALERT_OPERATIONS_READ,
            PERMISSION_TIMELINE_READ,
            PERMISSION_PREVENTIVE_CONTROL_READ,
            PERMISSION_TAXONOMY_READ,
            PERMISSION_EXPOSURE_PROFILE_READ,
        }
    ),
    UserRole.VIEWER: frozenset(
        {
            PERMISSION_INCIDENT_READ,
            PERMISSION_METRICS_READ,
            PERMISSION_INTEGRATION_READ,
        }
    ),
}


def role_has_permission(role: UserRole, permission: str) -> bool:
    allowed = _ROLE_PERMISSIONS.get(role, frozenset())
    return permission in allowed


def restricted_detection_authorised(db, user) -> bool:
    """Restricted fields follow membership role, never a leftover User.role column."""
    from app.services import organisation_access_service as org_access

    try:
        membership = org_access.require_active_membership(db, user)
    except org_access.OrganisationAccessError:
        return False
    return role_has_permission(membership.role, PERMISSION_RESTRICTED_DETECTION_READ)


def list_permissions_for_role(role: UserRole) -> list[str]:
    return sorted(_ROLE_PERMISSIONS.get(role, frozenset()))
