import { useCallback, useEffect, useState } from "react";
import { incidentGovernanceApi, type PreventiveControl } from "../../api/incidentGovernanceClient";
import { useAuth } from "../../context/AuthContext";
import { sanitizeString } from "../../utils/safety";
import Card from "../Card";
import StatusBadge from "../StatusBadge";

export default function PreventiveControlsPanel({ incidentId, rootCauseId }: { incidentId: string; rootCauseId?: string }) {
  const { can } = useAuth();
  const [controls, setControls] = useState<PreventiveControl[]>([]);
  const [reasons, setReasons] = useState<Record<string, string>>({});
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setControls((await incidentGovernanceApi.listPreventiveControls(incidentId)).controls); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Preventive controls could not be loaded."); } }, [incidentId]);
  useEffect(() => { void load(); }, [load]);
  const act = async (action: () => Promise<unknown>) => { setBusy(true); try { await action(); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Preventive-control action failed."); } finally { setBusy(false); } };
  const reasonFor = (control: PreventiveControl) => reasons[control.control_id] ?? "Reviewed against the incident evidence and implementation state.";
  return <Card title="Preventive Controls">{error ? <p className="mb-3 text-sm text-red-700">{sanitizeString(error)}</p> : null}{controls.length ? <div className="space-y-3">{controls.map((control) => <article key={control.control_id} className="rounded-md border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-2"><strong className="text-navy-900">{sanitizeString(control.control_name)}</strong><StatusBadge value={control.status} /><StatusBadge value={control.verification_status} /></div><p className="mt-2 text-sm text-navy-900">{sanitizeString(control.control_description)}</p><p className="mt-1 text-xs text-ink-subtle">Type: {control.control_type.replaceAll("_", " ")} | Source: {control.source}</p><input className="field-control mt-3 w-full" aria-label={`Reason for ${control.control_id}`} value={reasons[control.control_id] ?? ""} onChange={(event) => setReasons({ ...reasons, [control.control_id]: event.target.value })} placeholder="Auditable reason (optional default provided)" /><div className="mt-3 flex flex-wrap gap-2">{can("preventive_control:review") && control.status === "proposed" ? <button className="btn-secondary" disabled={busy} onClick={() => act(() => incidentGovernanceApi.reviewPreventiveControl(control.control_id, reasonFor(control)))}>Review</button> : null}{can("preventive_control:approve") && control.status === "reviewed" ? <button className="btn-secondary" disabled={busy} onClick={() => act(() => incidentGovernanceApi.approvePreventiveControl(control.control_id, reasonFor(control)))}>Approve</button> : null}{can("preventive_control:implement") && control.status === "approved" ? <button className="btn-secondary" disabled={busy} onClick={() => act(() => incidentGovernanceApi.implementPreventiveControl(control.control_id, reasonFor(control)))}>Mark implemented</button> : null}{can("preventive_control:verify") && control.status === "implemented" ? <button className="btn-secondary" disabled={busy} onClick={() => act(() => incidentGovernanceApi.verifyPreventiveControl(control.control_id, reasonFor(control)))}>Record verification</button> : null}</div></article>)}</div> : <p className="text-sm text-ink-muted">No preventive controls are proposed.</p>}{can("preventive_control:generate") ? <button className="btn-secondary mt-3" disabled={busy || !rootCauseId} onClick={() => rootCauseId && act(() => incidentGovernanceApi.generatePreventiveControls(incidentId, rootCauseId))}>Generate deterministic proposals</button> : null}<p className="mt-3 text-xs text-ink-subtle">Proposals require separate review, approval, implementation, and verification. They do not change production systems.</p></Card>;
}
