/** Frontend permission checks aligned with backend permission_service. */

export const ROLE_PERMISSIONS: Record<string, Set<string>> = {
  admin: new Set([
    "incident:read",
    "evidence:read",
    "evidence:upload",
    "evidence:load_sample",
    "workflow:parse",
    "workflow:detect",
    "workflow:analyse",
    "explanation:generate",
    "incident:review",
    "incident:review_read",
    "audit:read",
    "fix:verify",
    "fix:read",
    "report:generate",
    "metrics:read",
    "metrics:run",
    "user:manage",
    "integration:ingest",
    "integration:export",
    "integration:read",
    "integration:token_manage",
    "scanner_bridge:import",
    "scanner_bridge:read",
    "live_monitor:read",
    "live_monitor:control",
    "live_monitor:ingest",
    "live_monitor:incident",
    "live_monitor:dismiss",
    "ai_remediation:read",
    "ai_remediation:generate",
    "ai_remediation:review",
    "privacy_impact:read",
    "privacy_impact:assess",
    "privacy_impact:approve",
    "breach_alert:read",
    "breach_alert:manage",
    "affected_subject:read",
    "affected_subject:resolve",
    "containment:read",
    "containment:approve",
    "containment:execute",
    "customer_notification:read",
    "customer_notification:draft",
    "customer_notification:approve",
    "customer_notification:queue",
    "breach_decision:read",
    "breach_decision:create",
    "breach_decision:review",
    "breach_decision:approve",
    "provenance:read",
    "provenance:validate",
    "integrity:read",
    "integrity:verify",
    "counterfactual:read",
    "counterfactual:run",
    "alert_operations:read",
    "alert_operations:manage",
    "timeline:read",
    "preventive_control:read",
    "preventive_control:generate",
    "preventive_control:review",
    "preventive_control:approve",
    "preventive_control:implement",
    "preventive_control:verify",
    "taxonomy:read",
    "taxonomy:validate",
    "exposure_profile:read",
    "exposure_profile:recalculate",
    "exposure_profile:review",
    "restricted_detection:read",
  ]),
  security_analyst: new Set([
    "incident:read",
    "evidence:read",
    "evidence:upload",
    "evidence:load_sample",
    "workflow:parse",
    "workflow:detect",
    "workflow:analyse",
    "explanation:generate",
    "incident:review",
    "incident:review_read",
    "audit:read",
    "fix:verify",
    "fix:read",
    "report:generate",
    "metrics:read",
    "metrics:run",
    "integration:ingest",
    "integration:export",
    "integration:read",
    "integration:token_manage",
    "scanner_bridge:import",
    "scanner_bridge:read",
    "live_monitor:read",
    "live_monitor:control",
    "live_monitor:ingest",
    "live_monitor:incident",
    "live_monitor:dismiss",
    "ai_remediation:read",
    "ai_remediation:generate",
    "ai_remediation:review",
    "privacy_impact:read",
    "privacy_impact:assess",
    "breach_alert:read",
    "breach_alert:manage",
    "affected_subject:read",
    "affected_subject:resolve",
    "containment:read",
    "customer_notification:read",
    "customer_notification:draft",
    "breach_decision:read",
    "breach_decision:create",
    "breach_decision:review",
    "provenance:read",
    "provenance:validate",
    "integrity:read",
    "counterfactual:read",
    "counterfactual:run",
    "alert_operations:read",
    "alert_operations:manage",
    "timeline:read",
    "preventive_control:read",
    "preventive_control:generate",
    "preventive_control:review",
    "taxonomy:read",
    "exposure_profile:read",
    "exposure_profile:recalculate",
    "exposure_profile:review",
  ]),
  developer: new Set([
    "incident:read",
    "evidence:read",
    "fix:read",
    "integration:read",
    "scanner_bridge:read",
  ]),
  devsecops_engineer: new Set([
    "incident:read",
    "evidence:read",
    "evidence:upload",
    "workflow:parse",
    "workflow:detect",
    "workflow:analyse",
    "fix:verify",
    "fix:read",
    "report:generate",
    "metrics:read",
    "integration:ingest",
    "integration:export",
    "integration:read",
    "integration:token_manage",
    "scanner_bridge:import",
    "scanner_bridge:read",
    "live_monitor:read",
    "live_monitor:control",
    "live_monitor:ingest",
    "live_monitor:incident",
    "ai_remediation:read",
    "ai_remediation:generate",
    "ai_remediation:review",
    "containment:read",
    "containment:execute",
    "breach_decision:read",
    "provenance:read",
    "integrity:read",
    "integrity:verify",
    "counterfactual:read",
    "alert_operations:read",
    "timeline:read",
    "preventive_control:read",
    "preventive_control:implement",
    "preventive_control:verify",
    "taxonomy:read",
    "exposure_profile:read",
  ]),
  auditor: new Set([
    "incident:read",
    "incident:review_read",
    "audit:read",
    "fix:read",
    "report:generate",
    "metrics:read",
    "integration:export",
    "integration:read",
    "scanner_bridge:read",
    "live_monitor:read",
    "ai_remediation:read",
    "privacy_impact:read",
    "breach_alert:read",
    "affected_subject:read",
    "containment:read",
    "customer_notification:read",
    "breach_decision:read",
    "provenance:read",
    "integrity:read",
    "counterfactual:read",
    "alert_operations:read",
    "timeline:read",
    "preventive_control:read",
    "taxonomy:read",
    "exposure_profile:read",
  ]),
  viewer: new Set(["incident:read", "metrics:read", "integration:read"]),
};

ROLE_PERMISSIONS.organisation_admin = ROLE_PERMISSIONS.admin;
ROLE_PERMISSIONS.platform_admin = ROLE_PERMISSIONS.admin;

export function hasPermission(role: string | undefined, permission: string): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}

export const ROLE_LABELS: Record<string, string> = {
  admin: "Admin",
  organisation_admin: "Organisation Admin",
  platform_admin: "Platform Admin",
  security_analyst: "Security Analyst",
  developer: "Developer",
  devsecops_engineer: "DevSecOps Engineer",
  auditor: "Auditor",
  viewer: "Viewer",
};

